version: '3'

services:
  postgres:
    image: postgres:11.3

  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    image: web
    build:
      context: .
      dockerfile: compose/Dockerfile
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    ports:
      - "8080:8000"
    depends_on:
      - postgres
    env_file:
      - .env
